version: '3.5'
services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pessoasdb
    ports:
      - "5432:5432"
    volumes:
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.9GB'

  api01:
    image: hugoestevam/rinhabackend
    hostname: pessoasapi01
    depends_on:
      - db
    environment:
      - DB_CONNECTION_STRING=Host=db;Database=pessoasdb;Userid=postgres;Password=P@ssw0rd;SSL Mode=Disable;Maximum Pool Size=18;Enlist=false;Max Auto Prepare=4;Multiplexing=true;Write Coalescing Buffer Threshold Bytes=1000;
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1.0GB'
  
  api02:
    image: hugoestevam/rinhabackend
    hostname: pessoasapi01
    depends_on:
      - db
    environment:
      - DB_CONNECTION_STRING=Host=db;Database=pessoasdb;Userid=postgres;Password=P@ssw0rd;SSL Mode=Disable;Maximum Pool Size=18;Enlist=false;Max Auto Prepare=4;Multiplexing=true;Write Coalescing Buffer Threshold Bytes=1000;
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1.0GB'
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '0.1GB'

networks:
  default:
    driver: bridge
    name: rinhabackend